create table FANTASY_SUPPLIER (
    id number generated by default on null as identity,
    name varchar2(100) not null,
    description varchar2(4000) null,
    urlgeneral varchar2(1000) not null,
    urlweekproyection varchar2(1000),
    created date not null,
    created_by varchar2(255 char) not null,
    updated date not null,
    updated_by varchar2(255 char) not null,
    visualorder number(2,0) null
);

alter table FANTASY_SUPPLIER add constraint FANTASY_SUPPLIER_PK primary key (id);