create table FANTASY_POINT (
    id number generated by default on null as identity,
    idfantasyseason number(4,0) not null,
    week number(2,0) not null,
    idfantasyplayer number not null,
    fantasypoints number(5,2) not null,
    created date not null,
    created_by varchar2(255 char) not null,
    updated date not null,
    updated_by varchar2(255 char) not null
);

alter table FANTASY_POINT add constraint FANTASY_POINT_PK primary key (id);
alter table FANTASY_POINT add constraint FANTASY_POINT_FK foreign  key (idfantasyseason) references FANTASY_SEASON(id);
alter table FANTASY_POINT add constraint FANTASY_POINT_FK2 foreign  key (idfantasyplayer) references FANTASY_PLAYER(id);
alter table FANTASY_POINT add constraint FANTASY_POINT_UK unique (idfantasyseason, week, idfantasyplayer);