create table FANTASY_TEAM (
    id number generated by default on null as identity,
    team varchar2(50) not null,
    city varchar2(50) not null,
    urllogo varchar2(1000),
    created date not null,
    created_by varchar2(255 char) not null,
    updated date not null,
    updated_by varchar2(255 char) not null
);

alter table FANTASY_TEAM add constraint FANTASY_TEAM_PK primary key (id);