create table FANTASY_PROYECTION (
    id number generated by default on null as identity,
    idfantasyseason number(4,0) not null,
    week number(2,0) not null,
    idfantasysupplier number not null,
    idfantasyposition number not null,
    idfantasyplayer number not null,
    created date not null,
    created_by varchar2(255 char) not null,
    updated date not null,
    updated_by varchar2(255 char) not null
);

alter table FANTASY_PROYECTION add constraint FANTASY_PROYECTION_PK primary key (id);
alter table FANTASY_PROYECTION add constraint FANTASY_PROYECTION_FK foreign  key (idfantasyseason) references FANTASY_SEASON(id);
alter table FANTASY_PROYECTION add constraint FANTASY_PROYECTION_FK2 foreign  key (idfantasysupplier) references FANTASY_SUPPLIER(id);
alter table FANTASY_PROYECTION add constraint FANTASY_PROYECTION_FK3 foreign  key (idfantasyposition) references FANTASY_POSITION(id);
alter table FANTASY_PROYECTION add constraint FANTASY_PROYECTION_FK4 foreign  key (idfantasyplayer) references FANTASY_PLAYER(id);
alter table FANTASY_PROYECTION add constraint FANTASY_PROYECTION_UK unique (idfantasyseason, week, idfantasysupplier, idfantasyposition);