create table FANTASY_SEASON (
    id number generated by default on null as identity,
    season number(4,0) not null,
    descripcion varchar2(100) null,
    created date not null,
    created_by varchar2(255 char) not null,
    updated date not null,
    updated_by varchar2(255 char) not null
);

alter table FANTASY_SEASON add constraint FANTASY_SEASON_PK primary key (id);
alter table FANTASY_SEASON add constraint FANTASY_SEASON_UK unique (season);