create table FANTASY_VALUE (
    id number generated by default on null as identity,
    idfantasyseason number(4,0) not null,
    week number(2,0) not null,
    idfantasysupplier number not null,
    winpoint number(2,0) default 0 not null,
    created date not null,
    created_by varchar2(255 char) not null,
    updated date not null,
    updated_by varchar2(255 char) not null
);

alter table FANTASY_VALUE add constraint FANTASY_VALUE_PK primary key (id);
alter table FANTASY_VALUE add constraint FANTASY_VALUE_FK foreign  key (idfantasyseason) references FANTASY_SEASON(id);
alter table FANTASY_VALUE add constraint FANTASY_VALUE_FK2 foreign  key (idfantasysupplier) references FANTASY_SUPPLIER(id);
alter table FANTASY_VALUE add constraint FANTASY_VALUE_UK unique (idfantasyseason, week, idfantasysupplier);


