
-- Generated by ORDS REST Data Services 25.3.1.r2891312
-- Schema: WKSP_CURSO  Date: Wed Nov 12 04:50:30 2025 
--
        
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'curso',
      p_auto_rest_auth      => FALSE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'fantasy',
      p_base_path      => '/fantasy/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'fantasy',
      p_pattern        => 'workteam',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fantasy',
      p_pattern        => 'workteam',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from FANTASY_WORKTEAM 
WHERE 
  TRANSLATE(
    REPLACE(REPLACE(REPLACE(UPPER(WORKTEAM), '' '', ''''), ''.'', ''''), '''''''', ''''),
    ''ÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÄËÏÖÜÃÕÑÇ'',
    ''AEIOUAEIOUAEIOUAEIOUAONC''
  )
  =
  TRANSLATE(
    REPLACE(REPLACE(REPLACE(UPPER(NVL(:name, WORKTEAM)), '' '', ''''), ''.'', ''''), '''''''', ''''),
    ''ÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÄËÏÖÜÃÕÑÇ'',
    ''AEIOUAEIOUAEIOUAEIOUAONC''
  )');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'workteam',
      p_method             => 'GET',
      p_name               => 'NAME',
      p_bind_variable_name => 'name',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'fantasy',
      p_pattern        => 'season',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fantasy',
      p_pattern        => 'season',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM FANTASY_SEASON WHERE SEASON = NVL(:season, SEASON)');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'season',
      p_method             => 'GET',
      p_name               => 'SEASON',
      p_bind_variable_name => 'season',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'ejercicio concreto');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'fantasy',
      p_pattern        => 'player',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fantasy',
      p_pattern        => 'player',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT PL.ID, PL.IDFANTASYSEASON, PL.NAME, PL.IDFANTASYPOSITIONBASE, PL.CREATED, PL.CREATED_BY, PL.UPDATED, PL.UPDATED_BY, PL.URLPHOTO, PL.IDFANTASYTEAM, PL.IDFANTASYWORKTEAM,
    -- nueva columna con la posición base + posibles posiciones adicionales (separadas por ,)
    (SELECT LISTAGG(position, '','') WITHIN GROUP (ORDER BY is_base, position)
    FROM (
      SELECT DISTINCT fpb.position, 1 AS is_base
      FROM FANTASY_POSITION_BASE fpb
      WHERE fpb.id = PL.IDFANTASYPOSITIONBASE
      UNION
      SELECT DISTINCT fpb2.position, 2 AS is_base
      FROM FANTASY_PLAYER_POSITION_BASE_ADI adi
      JOIN FANTASY_POSITION_BASE fpb2 ON adi.IDFANTASYPOSITIONBASE = fpb2.ID
      WHERE adi.IDFANTASYPLAYER = PL.ID
    )
    ) POSITIONBASETOTALES
FROM FANTASY_PLAYER PL
WHERE PL.IDFANTASYSEASON = :idseason AND PL.IDFANTASYWORKTEAM = :idworkteam 
  AND 
      TRANSLATE(
        REPLACE(REPLACE(REPLACE(UPPER(NAME), '' '', ''''), ''.'', ''''), '''''''', ''''),
        ''ÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÄËÏÖÜÃÕÑ' || 'Ç'',
        ''AEIOUAEIOUAEIOUAEIOUAONC''
      )
      LIKE ''%'' ||
      TRANSLATE(
        REPLACE(REPLACE(REPLACE(UPPER(NVL(:name, NAME)), '' '', ''''), ''.'', ''''), '''''''', ''''),
        ''ÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÄËÏÖÜÃÕÑÇ'',
        ''AEIOUAEIOUAEIOUAEIOUAONC''
      )  || ''%''');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'player',
      p_method             => 'GET',
      p_name               => 'IDWORKTEAM',
      p_bind_variable_name => 'idworkteam',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'player',
      p_method             => 'GET',
      p_name               => 'IDSEASON',
      p_bind_variable_name => 'idseason',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'player',
      p_method             => 'GET',
      p_name               => 'NAME',
      p_bind_variable_name => 'name',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fantasy',
      p_pattern        => 'player',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'declare
  id_ FANTASY_PLAYER.ID%TYPE;
begin
  --ya existe y esta todo igual
  <<existe>>
  begin
    SELECT ID
    INTO id_
    FROM FANTASY_PLAYER
    WHERE IDFANTASYSEASON = :idseason 
      --mejor no, por los jugadores que puede tener varias. Comprobamos sin esto para no insertar dos veces mismo jugador, que daria error
      --AND IDFANTASYPOSITIONBASE = :idpositionbase 
      AND IDFANTASYTEAM = :idteam
      AND IDFANTASYWORKTEAM = :idworkteam
      AND 
          TRANSLATE(
            REPLACE(REPLACE(REPLACE(UPPER(NAME), '' '', ''''), ''.'', ''''), '''''''', ''''),
            ''ÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÄËÏÖÜÃÕÑÇ'',
            ''AEIOUAEIOUAEIOUAEIOUAONC''
          )
          LIKE ''%'' ||
          TRANSLATE(
            REPLACE(REPLACE(REPLACE(UPPER(NVL(:name, NAME)), '' '', ''''), ''.'', ''''), '''''''', ''''),
            ''ÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÄËÏÖÜÃÕÑÇ'',
            ''AEIOUAEIOUAEIOUAEIOUAONC''
          )  || ''%'';      

    :status := 200; -- y listo, no hay que hace nada
  exception
    wh' || 'en no_data_found then      
      --hay que crearlo
      INSERT INTO FANTASY_PLAYER(IDFANTASYSEASON, IDFANTASYPOSITIONBASE, IDFANTASYTEAM, IDFANTASYWORKTEAM, NAME, URLPHOTO)
      VALUES (:idseason, :idpositionbase, :idteam, :idworkteam, :name, :urlphoto);

      :status := 200; --inserto
  end existe;


exception
  when others then
    :status := 400;
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'player',
      p_method             => 'PUT',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'fantasy',
      p_pattern        => 'point',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fantasy',
      p_pattern        => 'point',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM FANTASY_POINT WHERE IDFANTASYSEASON = :idseason AND WEEK = :week AND IDFANTASYWORKTEAM = :idworkteam AND IDFANTASYPLAYER = NVL(:idplayer, IDFANTASYPLAYER)');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'point',
      p_method             => 'GET',
      p_name               => 'WEEK',
      p_bind_variable_name => 'week',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'point',
      p_method             => 'GET',
      p_name               => 'IDSEASON',
      p_bind_variable_name => 'idseason',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'point',
      p_method             => 'GET',
      p_name               => 'idworkteam',
      p_bind_variable_name => 'idworkteam',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'point',
      p_method             => 'GET',
      p_name               => 'IDPLAYER',
      p_bind_variable_name => 'idplayer',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fantasy',
      p_pattern        => 'point',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'declare
  id_ FANTASY_POINT.ID%TYPE;
begin
  --ya existe y esta todo igual
  <<todoigual>>
  begin
    SELECT ID
    INTO id_
    FROM FANTASY_POINT
    WHERE IDFANTASYSEASON = :idseason 
      AND WEEK = :week 
      AND IDFANTASYPLAYER = :idplayer
      AND IDFANTASYWORKTEAM = :idworkteam
      AND FANTASYPOINTS = :points;
    :status := 200; -- y listo, no hay que hace nada
  exception
    when no_data_found then      
      <<existePeroOtraPuntuacion>>
      begin
        SELECT ID
        INTO id_
        FROM FANTASY_POINT
        WHERE IDFANTASYSEASON = :idseason 
          AND WEEK = :week 
          AND IDFANTASYPLAYER = :idplayer
          AND IDFANTASYWORKTEAM = :idworkteam;
        
        UPDATE FANTASY_POINT
        SET FANTASYPOINTS = :points
        WHERE IDFANTASYSEASON = :idseason 
          AND WEEK = :week 
          AND IDFANTASYPLAYER = :idplayer
          AND IDFANTASYWORKTEAM = :idworkteam;

        :status := 200; --actualizo' || '
      exception
        when no_data_found then
          --hay que crearlo
          INSERT INTO FANTASY_POINT(IDFANTASYSEASON,WEEK,IDFANTASYPLAYER,IDFANTASYWORKTEAM,FANTASYPOINTS)
          VALUES (:idseason,:week,:idplayer,:idworkteam,:points);

          :status := 200; --inserto
      end existePeroOtraPuntuacion;

  end todoigual;


exception
  when others then
    :status := 400;
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'point',
      p_method             => 'PUT',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'fantasy',
      p_pattern        => 'supplier',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fantasy',
      p_pattern        => 'supplier',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM FANTASY_SUPPLIER 
WHERE
  TRANSLATE(
    REPLACE(REPLACE(REPLACE(UPPER(NAME), '' '', ''''), ''.'', ''''), '''''''', ''''),
    ''ÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÄËÏÖÜÃÕÑÇ'',
    ''AEIOUAEIOUAEIOUAEIOUAONC''
  )
  =
  TRANSLATE(
    REPLACE(REPLACE(REPLACE(UPPER(NVL(:name, NAME)), '' '', ''''), ''.'', ''''), '''''''', ''''),
    ''ÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÄËÏÖÜÃÕÑÇ'',
    ''AEIOUAEIOUAEIOUAEIOUAONC''
  )');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'supplier',
      p_method             => 'GET',
      p_name               => 'name',
      p_bind_variable_name => 'name',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'fantasy',
      p_pattern        => 'position',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fantasy',
      p_pattern        => 'position',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM FANTASY_POSITION WHERE POSITION = NVL(:position, POSITION)');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'position',
      p_method             => 'GET',
      p_name               => 'position',
      p_bind_variable_name => 'position',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'fantasy',
      p_pattern        => 'proyection',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fantasy',
      p_pattern        => 'proyection',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM FANTASY_PROYECTION WHERE IDFANTASYSEASON = :idseason AND WEEK = :week AND IDFANTASYWORKTEAM = :idworkteam
AND IDFANTASYSUPPLIER = NVL(:idsupplier, IDFANTASYSUPPLIER)');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'proyection',
      p_method             => 'GET',
      p_name               => 'idseason',
      p_bind_variable_name => 'idseason',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'proyection',
      p_method             => 'GET',
      p_name               => 'week',
      p_bind_variable_name => 'week',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'proyection',
      p_method             => 'GET',
      p_name               => 'idworkteam',
      p_bind_variable_name => 'idworkteam',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'proyection',
      p_method             => 'GET',
      p_name               => 'idsupplier',
      p_bind_variable_name => 'idsupplier',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fantasy',
      p_pattern        => 'proyection',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'declare
  id_ FANTASY_PROYECTION.ID%TYPE;
begin
  --ya existe y esta todo igual
  <<todoigual>>
  begin
    SELECT ID
    INTO id_
    FROM FANTASY_PROYECTION
    WHERE IDFANTASYSEASON = :idseason 
      AND WEEK = :week 
      AND IDFANTASYWORKTEAM = :idworkteam
      AND IDFANTASYSUPPLIER = :idsupplier
      AND IDFANTASYPOSITION = :idposition
      AND IDFANTASYPLAYER = :idplayer;
    :status := 200; -- y listo, no hay que hace nada
  exception
    when no_data_found then      
      <<existePeroOtroPlayer>>
      begin
        SELECT ID
        INTO id_
        FROM FANTASY_PROYECTION
        WHERE IDFANTASYSEASON = :idseason AND WEEK = :week AND IDFANTASYWORKTEAM = :idworkteam
          AND IDFANTASYSUPPLIER = :idsupplier
          AND IDFANTASYPOSITION = :idposition;
        
        --no puede ser nulo el jugador, si lo cargan asi, lo que tendremos que hacer es borrarlo
        IF :idplayer IS NULL THEN
            DELETE FROM FANTASY_PROYECTION
   ' || '         WHERE IDFANTASYSEASON = :idseason AND WEEK = :week AND IDFANTASYWORKTEAM = :idworkteam
              AND IDFANTASYSUPPLIER = :idsupplier
              AND IDFANTASYPOSITION = :idposition;
        ELSE
            UPDATE FANTASY_PROYECTION
            SET IDFANTASYPLAYER = :idplayer
            WHERE IDFANTASYSEASON = :idseason AND WEEK = :week AND IDFANTASYWORKTEAM = :idworkteam
              AND IDFANTASYSUPPLIER = :idsupplier
              AND IDFANTASYPOSITION = :idposition;
        END IF;

        :status := 200; --actualizo
      exception
        when no_data_found then
            --no puede ser nulo el jugador, si lo cargan asi, nunca insertaremos
            IF :idplayer IS NOT NULL THEN        
              --hay que crearlo
              insert into FANTASY_PROYECTION(IDFANTASYSEASON,WEEK,IDFANTASYSUPPLIER,IDFANTASYPOSITION,IDFANTASYPLAYER,IDFANTASYWORKTEAM)
              values(:idseason,:week,:idsupplier,:idposition,:idplayer,:idworkteam);
   ' || '         END IF;

          :status := 200; --inserto
      end existePeroOtroPlayer;

  end todoigual;


exception
  when others then
    :status := 400;
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'proyection',
      p_method             => 'PUT',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'fantasy',
      p_pattern        => 'team',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fantasy',
      p_pattern        => 'team',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT ID, CITY || '' '' || TEAM AS NAME, URLLOGO FROM FANTASY_TEAM 
WHERE
  TRANSLATE(
    REPLACE(REPLACE(REPLACE(UPPER(CITY || '' '' || TEAM ), '' '', ''''), ''.'', ''''), '''''''', ''''),
    ''ÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÄËÏÖÜÃÕÑÇ'',
    ''AEIOUAEIOUAEIOUAEIOUAONC''
  )
  =
  TRANSLATE(
    REPLACE(REPLACE(REPLACE(UPPER(NVL(:name, CITY || '' '' || TEAM)), '' '', ''''), ''.'', ''''), '''''''', ''''),
    ''ÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÄËÏÖÜÃÕÑÇ'',
    ''AEIOUAEIOUAEIOUAEIOUAONC''
  )');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'team',
      p_method             => 'GET',
      p_name               => 'name',
      p_bind_variable_name => 'name',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'fantasy',
      p_pattern        => 'positionbase',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fantasy',
      p_pattern        => 'positionbase',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM FANTASY_POSITION_BASE WHERE POSITION = NVL(:position, POSITION)');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'positionbase',
      p_method             => 'GET',
      p_name               => 'position',
      p_bind_variable_name => 'position',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'fantasy',
      p_pattern        => 'playerposadi',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fantasy',
      p_pattern        => 'playerposadi',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'declare
  aux_ VARCHAR2(1);
begin
  --ya existe
  
  SELECT ''X'' 
  INTO aux_ 
  FROM FANTASY_PLAYER_POSITION_BASE_ADI
  WHERE IDFANTASYPLAYER = :idplayer
    AND IDFANTASYPOSITIONBASE = :idpositionbase;      

  :status := 200; -- y listo, no hay que hace nada

exception
  when no_data_found then      
    --hay que crearlo
    INSERT INTO FANTASY_PLAYER_POSITION_BASE_ADI(IDFANTASYPLAYER, IDFANTASYPOSITIONBASE)
    VALUES (:idplayer, :idpositionbase);

    :status := 200; --inserto
  when others then
    :status := 400;
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'fantasy',
      p_pattern            => 'playerposadi',
      p_method             => 'PUT',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  l_modules(1) := 'fantasy';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'FANTASY_USER_PRIV',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'FANTASY_USER_PRIV',
      p_description    => NULL,
      p_comments       => NULL); 

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;


COMMIT;

END;