prompt --application/deployment/install/install_03_carga_inserciones_base
begin
--   Manifest
--     INSTALL: INSTALL-03_carga_inserciones_base
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.10.07'
,p_release=>'22.2.1'
,p_default_workspace_id=>7231611737995830
,p_default_application_id=>102
,p_default_id_offset=>0
,p_default_owner=>'WKSP_CURSO'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(18840075250121164)
,p_install_id=>wwv_flow_imp.id(17317298307119342)
,p_name=>'03_carga_inserciones_base'
,p_sequence=>30
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'',
'PROMPT Insercion inicial en FANTASY_SUPPLIER',
'insert into FANTASY_SUPPLIER (name, description, urlgeneral, urlweekproyection, visualorder)',
'values(',
'  ''FantasyPros'',',
'  ''Since 2010, FantasyPros has aggregated and rated fantasy sports expert advice from around the web to make it easy for you to make the best decisions while drafting, managing your team, or playing daily fantasy sports. Our innovative tools and cont'
||'ent provide the easiest way to get the latest news and most accurate advice to help you win at fantasy sports.'',',
'  ''https://www.fantasypros.com/'',',
'  ''https://www.fantasypros.com/nfl/rankings/ppr-rb.php'',',
'  1',
');',
'',
'insert into FANTASY_SUPPLIER (name, description, urlgeneral, urlweekproyection, visualorder)',
'values(',
'  ''FantasyPros Top10'',',
'  ''La misma que FantasyPros, pero filtramos por el top 10 de aciertos'',',
'  ''https://www.fantasypros.com/'',',
'  ''https://www.fantasypros.com/nfl/rankings/ppr-rb.php'',',
'  2',
');',
'',
'',
'insert into FANTASY_SUPPLIER (name, description, urlgeneral, urlweekproyection, visualorder)',
'values(',
'  ''Estadio Fantasy'',',
'  '''',',
'  ''https://estadiofantasy.com/'',',
'  ''https://estadiofantasy.com/rankings-semanales-consenso/'',',
'  3',
');',
'',
'',
'insert into FANTASY_SUPPLIER (name, description, urlgeneral, urlweekproyection, visualorder)',
'values(',
'  ''FFToday'',',
'  ''A Fantasy Football Community'',',
'  ''https://www.fftoday.com/myfftoday/'',',
'  ''https://www.fftoday.com/rankings/playerwkproj.php?LeagueID=166045'',',
'  4',
');',
'',
'insert into FANTASY_SUPPLIER (name, description, urlgeneral, urlweekproyection, visualorder)',
'values(',
'  ''Football Guys'',',
'  ''With 600,000+ opted-in subscribers, our Daily Update newsletter is one of the most popular sports newsletters in the world. Our daily email gathers every bit of news from around the NFL and summarizes it in a quick and easy-to-understand format, w'
||'ith analysis and actionable insight on what it means for our reader''''s fantasy football leagues.',
'',
'Over the last 20 years, we''''ve built a passionate and loyal audience of fantasy football and sports fans, including prominent figures at major sports networks, and NFL players and personnel. Our writers and content have received numerous awards, incl'
||'uding the recent election of our co-founder and CEO Joe Bryant to the highest honor in the fantasy industry: The Fantasy Sports and Gaming Association''''s Fantasy Football Hall of Fame.',
'',
'For select partners who we believe in, and who would benefit our audience, we''''re offering an opportunity to grow your brand with the trust and confidence we''''ve built over the last 20 years.'',',
'  ''https://www.footballguys.com/'',',
'  ''https://league.footballguys.com/#fbgroster/roster/playerlist'',',
'  5',
');',
'',
'insert into FANTASY_SUPPLIER (name, description, urlgeneral, urlweekproyection, visualorder)',
'values(',
'  ''numberFire'',',
'  ''numberFire is the next generation sports analytics platform. We take the unstructured and misleading data that exists all around sports and mine it for unprecedented insight that allows us to predict player and team performance better than any com'
||'petitor.',
'',
'The first step of our process involves digging into the box score. We know that it means a lot more to throw for 300 yards against the Steelers than it does against the Browns, so why simply use yards as an indicator for how good a quarterback is? Us'
||'ing a series of mathematical models, we break down the action in order to have a better and more accurate understanding of what teams and players are performing well and which are paper champions.',
'',
'The next step of process involves using the power of predictive and regressive modeling to more accurately project future performance. Using our advanced metrics combined with state-of-the-art predictive algorithms, we leverage the power of science t'
||'o come up with the most accurate, data-driven projections around.',
'',
'We do all the number crunching - all you have to do is win. And win you will: if you used our fantasy projections instead of the platform defaults, you''''d have a 30% higher chance of winning your league.'',',
'  ''https://www.numberfire.com/nfl'',',
'  ''https://www.numberfire.com/nfl/fantasy/my-teams/teams/109490'',',
'  6',
');',
'',
'insert into FANTASY_SUPPLIER (name, description, urlgeneral, urlweekproyection, visualorder)',
'values(',
'  ''FantasyData'',',
'  ''FantasyData was founded in 2008, and has grown to become a leading sports data company, providing real-time and post-game feeds across all major sports to both the fantasy and other industries.',
'',
'FantasyData was created by CEO Scott Gimpel out of necessity when a need for sports data feeds on a different project was met with a lack of market options and steep pricing for start-ups from incumbent competitors. Our first few years in operation w'
||'ere marked with slow organic growth by providing NFL feeds to various fantasy companies. Starting in 2013, FantasyData made a push into the global sports data market by launching new sports and more comprehensive coverage. Today, we provide general a'
||'nd fantasy-specific feeds for all major professional and college sports, golf, NASCAR and top domestic & international soccer leagues.',
'',
'Headquartered in Philadelphia PA, FantasyData is privately held and debt-free, servicing more than 150 clients globally from fantasy & gaming to mobile, web and broadcasting industries.'',',
'  ''https://fantasydata.com/nfl'',',
'  ''https://fantasydata.com/nfl/fantasy-football-weekly-projections'',',
'  7',
');',
'',
'',
'insert into FANTASY_SUPPLIER (name, description, urlgeneral, urlweekproyection, visualorder)',
'values(',
'  ''Walter Football'',',
'  '''',',
'  ''https://walterfootball.com/index.php'',',
'  ''https://walterfootball.com/fantasyweeklyrankings.php'',',
'  8',
');',
'',
'',
'insert into FANTASY_SUPPLIER (name, description, urlgeneral, urlweekproyection, visualorder)',
'values(',
'  ''Roto Baller'',',
'  ''If you''''re looking to contact the RotoBaller team, then you''''re at the right place. We can be reached via a variety of different methods listed below.',
'',
'If you are looking to speak with our sports writers, fantasy analysts, site editors, marketing, advertising or PR teams - you can get in touch through the below channels and we will be glad to respond and put you in touch with the proper folks:'',',
'  ''https://www.rotoballer.com/nfl'',',
'  ''https://www.rotoballer.com/who-should-i-start-fantasy-football-weekly-matchups?src=bar'',',
'  9',
');',
'',
'insert into FANTASY_SUPPLIER (name, description, urlgeneral, urlweekproyection, visualorder)',
'values(',
'  ''Fantasy SP'',',
'  ''FantasySP is a fantasy sports site born out of necessity for my own fantasy sports needs back in 2007. I was in college, studying to get my degree in history and in my spare time would build FantasySP. The original idea was simple: to figure out a'
||' better way to get the news about your players faster than opponents in my league.',
'',
'I had no idea what FantasySP would be or if it was even worth building at the time, but I knew I would use it for my own needs. If others decided to use it too that would be great. I quit my job and gave it a shot fulltime to see how far I could take'
||' it.',
'',
'From that basic idea grew a ton of other ideas and features over the years that became industry standards as of today. I was one of the first to invent the tech and business model playbook that has been imitated by dozens of companies with millions o'
||'f dollars in funding.',
'',
'Today we have a wide set of features, offering users multiple tools and services to help manage their fantasy teams. We can take you all the way from draft season up until the final week of your fantasy season.'',',
'  ''https://www.fantasysp.com/nfl/'',',
'  ''https://www.fantasysp.com/start-sit-tool/nfl'',',
'  10',
');',
'',
'',
'',
'PROMPT Insercion inicial en FANTASY_POSITION',
'insert into FANTASY_POSITION (position, name, visualorder)',
'values(',
'  ''QB'',',
'  ''Quaterback'',',
'  1',
');',
'',
'insert into FANTASY_POSITION (position, name, visualorder)',
'values(',
'  ''RB1'',',
unistr('  ''1\00BA Runningback'','),
'  2',
');',
'',
'insert into FANTASY_POSITION (position, name, visualorder)',
'values(',
'  ''RB2'',',
unistr('  ''2\00BA Runningback'','),
'  3',
');',
'',
'insert into FANTASY_POSITION (position, name, visualorder)',
'values(',
'  ''WR1'',',
unistr('  ''1\00BA Wide Receiver'','),
'  4',
');',
'',
'insert into FANTASY_POSITION (position, name, visualorder)',
'values(',
'  ''WR2'',',
unistr('  ''2\00BA Wide Receiver'','),
'  5',
');',
'',
'insert into FANTASY_POSITION (position, name, visualorder)',
'values(',
'  ''TE'',',
'  ''Tigh End'',',
'  6',
');',
'',
'insert into FANTASY_POSITION (position, name, visualorder)',
'values(',
'  ''FLEX'',',
'  ''Flex Standard'',',
'  7',
');',
'',
'',
'PROMPT Insercion inicial en equipos',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Cardinals'',''Arizona'',''https://static.www.nfl.com/image/private/f_auto/league/u9fltoslqdsyao8cpm0k'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Falcons'',''Atlanta'',''https://static.www.nfl.com/image/private/f_auto/league/d8m7hzpsbrl6pnqht8op'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Panthers'',''Carolina'',''https://static.www.nfl.com/image/private/f_auto/league/ervfzgrqdpnc7lh5gqwq'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Bears'',''Chicago'',''https://static.www.nfl.com/image/private/f_auto/league/ra0poq2ivwyahbaq86d2'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Cowboys'',''Dallas'',''https://static.www.nfl.com/image/private/f_auto/league/ieid8hoygzdlmzo0tnf6'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Lions'',''Detroit'',''https://res.cloudinary.com/nflleague/image/private/f_auto/league/ocvxwnapdvwevupe4tpr'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Packers'',''Green Bay'',''https://res.cloudinary.com/nflleague/image/private/f_auto/league/gppfvr7n8gljgjaqux2x'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Rams'',''Los Angeles'',''https://static.www.nfl.com/image/private/f_auto/league/ayvwcmluj2ohkdlbiegi'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Vikings'',''Minnesota'',''https://res.cloudinary.com/nflleague/image/private/f_auto/league/teguylrnqqmfcwxvcmmz'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Saints'',''New Orleans'',''https://static.www.nfl.com/image/private/f_auto/league/grhjkahghjkk17v43hdx'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Giants'',''New York'',''https://res.cloudinary.com/nflleague/image/private/f_auto/league/t6mhdmgizi6qhndh8b9p'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Eagles'',''Philadelphia'',''https://res.cloudinary.com/nflleague/image/private/f_auto/league/puhrqgj71gobgdkdo6uq'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''49ers'',''San Francisco'',''https://res.cloudinary.com/nflleague/image/private/f_auto/league/dxibuyxbk0b9ua5ih9hn'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Seahawks'',''Seattle'',''https://res.cloudinary.com/nflleague/image/private/f_auto/league/gcytzwpjdzbpwnwxincg'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Buccaneers'',''Tampa Bay'',''https://static.www.nfl.com/image/private/f_auto/league/v8uqiualryypwqgvwcih'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Commanders'',''Washington'',''https://static.www.nfl.com/image/private/f_auto/league/xymxwrxtyj9fhaemhdyd'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Ravens'',''Baltimore'',''https://res.cloudinary.com/nflleague/image/private/f_auto/league/ucsdijmddsqcj1i9tddd'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Bills'',''Buffalo'',''https://res.cloudinary.com/nflleague/image/private/f_auto/league/giphcy6ie9mxbnldntsf'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Bengals'',''Cincinnati'',''https://res.cloudinary.com/nflleague/image/private/f_auto/league/okxpteoliyayufypqalq'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Browns'',''Cleveland'',''https://static.www.nfl.com/image/private/f_auto/league/fgbn8acp4opvyxk13dcy'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Broncos'',''Denver'',''https://res.cloudinary.com/nflleague/image/private/f_auto/league/t0p7m5cjdjy18rnzzqbx'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Texans'',''Houston'',''https://static.www.nfl.com/image/private/f_auto/league/bpx88i8nw4nnabuq0oob'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Colts'',''Indianapolis'',''https://static.www.nfl.com/image/private/f_auto/league/ketwqeuschqzjsllbid5'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Jaguars'',''Jacksonville'',''https://res.cloudinary.com/nflleague/image/private/f_auto/league/qycbib6ivrm9dqaexryk'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Chiefs'',''Kansas City'',''https://res.cloudinary.com/nflleague/image/private/f_auto/league/ujshjqvmnxce8m4obmvs'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Raiders'',''Las Vegas'',''https://static.www.nfl.com/image/private/f_auto/league/gzcojbzcyjgubgyb6xf2'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Chargers'',''Los Angeles'',''https://static.www.nfl.com/image/private/f_auto/league/dhfidtn8jrumakbogeu4'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Dolphins'',''Miami'',''https://res.cloudinary.com/nflleague/image/private/f_auto/league/lits6p8ycthy9to70bnt'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Patriots'',''New England'',''https://res.cloudinary.com/nflleague/image/private/f_auto/league/moyfxx3dq5pio4aiftnc'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Jets'',''New York'',''https://static.www.nfl.com/image/private/f_auto/league/ekijosiae96gektbo4iw'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Steelers'',''Pittsburgh'',''https://res.cloudinary.com/nflleague/image/private/f_auto/league/xujg9t3t4u5nmjgr54wx'');',
'insert into FANTASY_TEAM (team, city, urllogo)',
'values(''Titans'',''Tennessee'',''https://static.www.nfl.com/image/private/f_auto/league/pln44vuzugjgipyidsre'');'))
);
wwv_flow_imp.component_end;
end;
/
