prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@workspace/credentials/google_sso.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_zapp_negro_jpeg.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/reader_rights.sql
@@application/shared_components/security/authorizations/contribution_rights.sql
@@application/shared_components/security/app_access_control/administrator.sql
@@application/shared_components/security/app_access_control/contributor.sql
@@application/shared_components/security/app_access_control/reader.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/carga_temporada_actual.sql
@@application/shared_components/logic/application_processes/carga_equipo_fantasy_defecto.sql
@@application/shared_components/logic/application_items/equipo_fantasy_inicio.sql
@@application/shared_components/logic/application_items/id_equipo_fantasy_inicio.sql
@@application/shared_components/logic/application_items/id_temporada_actual.sql
@@application/shared_components/logic/application_items/temporada_actual.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/baja_activo_entero.sql
@@application/shared_components/user_interface/lovs/email_username_format.sql
@@application/shared_components/user_interface/lovs/equipos_existentes.sql
@@application/shared_components/user_interface/lovs/equipos_fantasy.sql
@@application/shared_components/user_interface/lovs/fuentes_posibles.sql
@@application/shared_components/user_interface/lovs/posiciones_base_jugador.sql
@@application/shared_components/user_interface/lovs/posiciones_jugador.sql
@@application/shared_components/user_interface/lovs/puntuacion_proveedor.sql
@@application/shared_components/user_interface/lovs/semanas.sql
@@application/shared_components/user_interface/lovs/sino_y_n.sql
@@application/shared_components/user_interface/lovs/temporadas_existentes.sql
@@application/shared_components/user_interface/lovs/tipo_long_term.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/google.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00030.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/pages/page_10011.sql
@@application/pages/page_10012.sql
@@application/pages/page_10013.sql
@@application/pages/page_10014.sql
@@application/pages/page_10020.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_01_carga_tablas.sql
@@application/deployment/install/install_02_carga_triggers.sql
@@application/deployment/install/install_03_carga_inserciones_base.sql
@@application/deployment/install/install_delta_2_0_sql.sql
@@application/deployment/install/install_delta_2_2_sql.sql
@@application/deployment/install/install_delta_2_4_sql.sql
@@application/deployment/install/install_delta_2_5_sql.sql
@@application/deployment/install/install_delta_2_6_sql.sql
@@application/deployment/install/install_delta_2_7_sql.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
